Rails.application.routes.draw do
get('/', {:controller => 'photos', :action => 'index'})
get('/photos/:id', {:controller => 'photos', :action => 'show'})
get('/new_photo', {:controller => 'photos', :action => 'new'})
get('/create_photo', {:controller => 'photos', :action => 'create'})
get('/photos/:id/Edit', {:controller => 'photos', :action => 'edit'})
get('/update_photo/:id', {:controller => 'photos', :action => 'update'})
get('/photos', {:controller => 'photos', :action => 'index'})
get('/photos/:id/destroy', {:controller => 'photos', :action => 'destroy'})
get('/photos/:id/like', {:controller => 'photos', :action => 'like'})
get('/shop', {:controller => 'items', :action => 'shop'})
get('/newmerch', {:controller => 'items', :action => 'new'})
get('/create_item', {:controller => 'items', :action => 'create'})
get('/items/:id/destroy', {:controller => 'items', :action => 'destroy'})
get('/items/:id/edit', {:controller => 'items', :action => 'edit'})
get('/items/:id/update', {:controller => 'items', :action => 'update'})
get('/sold-out', {:controller => 'items', :action => 'show'})
end
